services:
  db-main:
    image: ghcr.io/bandwidth-gig-guide/db-main:latest
    container_name: db-main
    volumes:
      - db-main-data:/var/lib/postgresql/data
    networks:
      - network-bandwidth

  service-public:
    image: ghcr.io/bandwidth-gig-guide/service-public:latest
    container_name: service-public
    networks:
      - network-bandwidth

  service-admin:
    image: ghcr.io/bandwidth-gig-guide/service-admin:latest
    container_name: service-admin
    networks:
      - network-bandwidth

  website-main:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_MODE: development
    container_name: website-main
    networks:
      - network-bandwidth
    environment:
      - APP_MODE=development
    volumes:
      - ./app:/app
      - /app/node_modules

  website-admin:
    image: ghcr.io/bandwidth-gig-guide/website-admin:latest
    container_name: website-admin
    networks:
      - network-bandwidth

  api-gateway:
    image: ghcr.io/bandwidth-gig-guide/api-gateway:latest
    container_name: api-gateway
    depends_on:
      - service-public
      - service-admin
      - website-main
      - website-admin
    ports:
      - "80:80"
    networks:
      - network-bandwidth

  db-auth:
    image: ghcr.io/bandwidth-gig-guide/db-auth:latest
    container_name: db-auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-auth
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-password
    volumes:
      - db-auth-data:/var/lib/postgresql/data
    networks:
      - network-bandwidth

  service-auth:
    image: ghcr.io/bandwidth-gig-guide/service-auth:latest
    container_name: service-auth
    restart: unless-stopped
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME: auth.localhost
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-auth:5432/db-auth
      KC_DB_USERNAME: db-user
      KC_DB_PASSWORD: db-password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - network-bandwidth

  service-monitor:
    image: ghcr.io/bandwidth-gig-guide/service-monitor:latest
    container_name: service-monitor
    restart: unless-stopped
    networks:
      - network-bandwidth

volumes:
  db-main-data:
  db-auth-data:

networks:
  network-bandwidth:
    driver: bridge
