services:
  db-main:
    image: ghcr.io/bandwidth-gig-guide/db-main:latest
    container_name: db-main
    env_file:
      - dev.env
    volumes:
      - db-main-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bandwidth

  website-main:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    container_name: website-main
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - db-main
    networks:
      - bandwidth

  service-public:
    image: ghcr.io/bandwidth-gig-guide/service-public:latest
    container_name: service-public
    restart: unless-stopped
    env_file:
      - dev.env
    depends_on:
      - db-main
    networks:
      - bandwidth

  reverse-proxy:
    image: caddy:2-alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - reverse-proxy-data:/data
      - reverse-proxy-config:/config
      - ./dev.Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - website-main
      - service-public
    networks:
      - bandwidth

volumes:
  db-main-data:
  reverse-proxy-data:
  reverse-proxy-config:

networks:
  bandwidth:
    driver: bridge
