services:
  db-main:
    image: ghcr.io/bandwidth-gig-guide/db-main:latest
    container_name: db-main
    networks:
      - network-bandwidth

  service-event:
    image: ghcr.io/bandwidth-gig-guide/service-event:latest
    container_name: service-event
    networks:
      - network-bandwidth

  service-artist:
    image: ghcr.io/bandwidth-gig-guide/service-artist:latest
    container_name: service-artist
    networks:
      - network-bandwidth

  service-venue:
    image: ghcr.io/bandwidth-gig-guide/service-venue:latest
    container_name: service-venue
    networks:
      - network-bandwidth

  service-account:
    image: ghcr.io/bandwidth-gig-guide/service-account:latest
    container_name: service-account
    networks:
      - network-bandwidth

  api-gateway:
    image: ghcr.io/bandwidth-gig-guide/api-gateway:latest
    container_name: api-gateway
    depends_on:
      - service-event
      - service-artist
      - service-venue
      - service-account
    ports:
      - "80:80"
    networks:
      - network-bandwidth

networks:
  network-bandwidth:
    driver: bridge
