export const TAGS = [
    'Acoustic',
    'Alternative',
    'Blues',
    'Classical',
    'Country',
    'Disco',
    'Electronic',
    'Experimental',
    'Folk',
    'Funk',
    'Garage',
    'Grunge',
    'Hardcore',
    'Hip Hop',
    'Indie',
    'Jazz',
    'Metal',
    'Pop',
    'Post Punk',
    'Post Rock',
    'Progressive Rock',
    'Psychedelic',
    'Punk',
    'R&B',
    'Reggae',
    'Rock',
    'Shoegaze',
    'Soul'
];